name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install
        working-directory: ./skillchain-info

      - name: Run tests
        run: npm test -- --watchAll=false
        working-directory: ./skillchain-info

      - name: Build React app
        run: npm run build
        working-directory: ./skillchain-info

      - name: Build Docker image
        run: docker build -t yourdockerhubusername/skillchain-info:latest ./skillchain-info

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker image
        run: docker push yourdockerhubusername/skillchain-info:latest